set(_CATKIN_CURRENT_PACKAGE "cvcar")
set(cvcar_VERSION "0.0.0")
set(cvcar_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(cvcar_PACKAGE_FORMAT "1")
set(cvcar_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(cvcar_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(cvcar_BUILDTOOL_DEPENDS "catkin")
set(cvcar_BUILDTOOL_EXPORT_DEPENDS )
set(cvcar_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(cvcar_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(cvcar_TEST_DEPENDS )
set(cvcar_DOC_DEPENDS )
set(cvcar_DEPRECATED "")