set(_CATKIN_CURRENT_PACKAGE "ros_caffe")
set(ros_caffe_VERSION "0.0.0")
set(ros_caffe_MAINTAINER "darrenl <tzu.ta.lin@gmail.com>")
set(ros_caffe_PACKAGE_FORMAT "1")
set(ros_caffe_BUILD_DEPENDS "roscpp" "std_msgs" "opencv2" "image_transport" "sensor_msgs" "cv_bridge")
set(ros_caffe_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "opencv2" "image_transport" "sensor_msgs" "cv_bridge")
set(ros_caffe_BUILDTOOL_DEPENDS "catkin")
set(ros_caffe_BUILDTOOL_EXPORT_DEPENDS )
set(ros_caffe_EXEC_DEPENDS "roscpp" "std_msgs" "opencv2" "image_transport" "sensor_msgs" "cv_bridge")
set(ros_caffe_RUN_DEPENDS "roscpp" "std_msgs" "opencv2" "image_transport" "sensor_msgs" "cv_bridge")
set(ros_caffe_TEST_DEPENDS )
set(ros_caffe_DOC_DEPENDS )
set(ros_caffe_DEPRECATED "")